minimum_pre_commit_version: 2.2.0
default_language_version:
    python: python3
default_stages: [commit]
fail_fast: true
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: check-added-large-files
        args: [--maxkb=500]
    -   id: end-of-file-fixer
        files: ^.ipynb
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
    -   id: mypy
        name: mypy --strict
        entry: >
            mypy --strict --show-error-codes persistable
        args: [--ignore-missing-imports]
        pass_filenames: false
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: pytest
        pass_filenames: false
        always_run: true
        language: system
        types: [python]
        stages: [push]
        verbose: true
