language: python

# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: '3.6'
    - python: '3.7'
    - python: '3.8'
    - python: '3.9'
    - python: '3.10'
      dist: xenial
      sudo: true

# Install Dependencies
install:
  - pip install .

# Tests
script:
 - pytest