# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build & Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    name: Setup ${{ matrix.python }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-18.04, ubuntu-20.04]
        python: [3.9.13, 3.10.4]
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: setup-python ${{ matrix.python }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}

    - name: Validate version
      run: |
        $pythonVersion = (python --version)
        if ("Python ${{ matrix.python }}" -ne "$pythonVersion"){
          Write-Host "The current version is $pythonVersion; expected version is ${{ matrix.python }}"
          exit 1
        }
        $pythonVersion
      shell: pwsh

    - name: Build Package
      run: |
        python -m pip install --upgrade pip
        pip install ".[dev]"

    - name: Test Package
      run: pytest

    - name: Test Examples
      run: |
        pip install treon
        treon
